### PR TITLE
openfl 3.5.3 support and animateUVs2 added

### PR DESCRIPTION
**Pull request by peteshand**
OpenFL 3.5.3 support added
support to be able to animate offsetU, offsetV, scaleU, scaleV on secondaryUVs added
Lots of getters and setters changed to use shorthand version, eg 
var name(get, set):Int
instead of
var name(get_name, set_name):Int

### CODE REVIEW

**Comment by peteshand** [comment]
Let me know if there is anything you'd like me to change before this can be merged.

**Comment by Greg209** [comment]
Thanks for the PR. One quick question. Any special reason for changing the filters3d to be Vector<Dynamic> rather than Array<Filter3DBase>?  My preference would be to maintain typing and the ability to do view3d.filters3d = [ a 3d filter, another 3d filter ];

**Comment by peteshand** [comment]
Hey Grey, yeah fair call regarding the Vector<Filter3DBase> stuff, I think I had some conflicts with a library that extends Away3d or resolved it incorrectly. I've reverted to use Vector<Filter3DBase> instead. Also are you planning on making an update on haxelib at some stage?

**Comment by Greg209** [comment]
Yes - definitely want to do an update and haxelib release, hopefully will find some time over the next few days. It'll be more of a compatability update (thanks to your PR) and other changes along the way and version updates. No major changes.

**Comment by peteshand** [comment]
Cool, yeah the only real issue has to do with openfl 3.5.3 incompatibilities.

**Comment by Justinfront** [comment]
I am still keen to see NME supported as well?

**Comment by peteshand** [comment]
Hey @Justinfront 

What exactly do you mean by "NME support", do you mean using NME as the underlying renderer for Away3D, or you simply would like to mix NME and Away3D in the same application?

**Comment by Justinfront** [comment]
These submodules I would need to port to NME to be able to port our Kiosk apps to haxe.
https://github.com/Justinfront/cib_submodules/tree/master/lib
I have no interest loosing weekends trying to work out why Openfl will not setup properly on a mac, I have used nme and openfl for a long time on experiments and they are both great products but nme can be setup from terminal, openfl setup is more of a lottery, and the main reason I have been reluctant to try to pitch in with greg's away3d port, I much prefer to explore luxe and kha that setup easily.  Also in terms of NME it would be great to have acadnme away3d version.

**Comment by peteshand** [comment]
OpenFL setup is super easy in FlashDevelop, maybe you could run it in BootCamp or a VM.

But yeah wow, those are a lot of libraries. If you're not interested in OpenFL it's probably not just help to you, but a lot of them have been ported to OpenFL.
* Away3D: https://github.com/away3d/away3d-core-openfl
* Starling 1.7: https://github.com/Haxeling/haxe-starling
* Robotlegs: https://github.com/robotlegs/openfl-robotlegs-framework (With Signals, Away3D and starling support)
* Swiftsuspenders: https://github.com/robotlegs/openfl-swiftsuspenders

Easily replaced:
* GreenSock-AS3: Replace with Actuate
* as3-signals: Replace with MSignal

Obsolete
* robotlegs-extensions-SARS and robotlegs-extensions-SignalCommandMap (Signals, Away3D and Starling support are all baked into the Haxe Robotlegs port)
* Starling-Extension-Graphics: graphics support baked into Starling 1.7 through Canvas object.

The rest are missing as far as I know.

**Comment by Justinfront** [comment]
What are the current show stoppers for away3d NME support?

**Comment by Greg209** [comment]
As far as Away3d for NME, as far as I know (cos I haven't touched NME for ages), primarily it's the implementation of Stage3D that needs porting back, which shouldn't be too big a deal really but I've just not had time.

As for Mac OpenFl setup, I've not really had a problem with it and now there is an installer AFAIK (but I've not had reason to try it as it's been working fine for me all along).

**Comment by fresh-flash** [comment]
@peteshand, thanks for a big update. In Cast.hx line 29 also change `ByteArray` to `ByteArrayData`.
Also what about html5 perfomance?
Using last libraries and this update I get 5-10 fps at html5 target.
Using away3d 1.1.0, lime 2.7.0, openfl 3.3.9 I get stable 60 fps at html5.
Flash target gives always 60 fps.

**Comment by peteshand** [comment]
Hey @fresh-flash
Do you have a staging link you can share?
If you open the comsole are you seeing any WebGL errors?
Also are you running in Release or Debug?

**Comment by fresh-flash** [comment]
@peteshand, sorry for trouble, it was cache of old version, now all works perfect on all targets. Thanks)

**Comment by peteshand** [comment]
@fresh-flash no worries, good to hear everything is working well for you now.

**Pull request merged**
